# Generated by Django 4.2.13 on 2024-06-20 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soac_users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='phone',
        ),
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(default='Johannesburg', max_length=100),
        ),
    ]
