# Generated by Django 4.2.13 on 2024-06-23 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soac_users', '0002_remove_profile_phone_profile_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, default='Johannesburg', max_length=100),
        ),
    ]
