# Generated by Django 4.2.13 on 2024-07-10 07:59

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soac_users', '0004_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/dd1jqwp94/image/upload/v1720597929/default_dktxl8.jpg', max_length=255, verbose_name='image'),
        ),
    ]
