# Generated by Django 5.0.6 on 2024-06-19 12:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soac_base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('body', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='soac_base.question')),
            ],
        """
        ),
<<<<<<< HEAD
        migrations.DeleteModel(
            name='Comment',
        """
        ),
=======
       # migrations.DeleteModel(
       #     name='Comment',
        #),
>>>>>>> ea297960173fadd140b862533dd62078ae21525b
    ]
